CREATE DATABASE checkout;

USE checkout;

CREATE TABLE IF NOT EXISTS purchases (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `address` VARCHAR(50) NULL DEFAULT NULL,
  `creditCard` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);